name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0']
        path:
          - tests

    name: PHP ${{ matrix.php }} tests for ${{ matrix.path }}
    steps:
      -   uses: actions/checkout@v2

      -   uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            coverage: none # disable xdebug, pcov

      -   uses: "ramsey/composer-install@v1"

      -   run: vendor/bin/phpunit ${{ matrix.path }} 

